name: Build LaTeX document
on: [push]
jobs:
   build_latex:
     runs-on: ubuntu-latest
     steps:
       - name: Set up Git repository
         uses: actions/checkout@v2
       - name: pdflatex statements
         uses: dante-ev/latex-action@latest
         with:
           root_file: f21_represntation.tex
           compiler: pdflatex

       - name: Results
         uses: appleboy/telegram-action@master
         with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            document: f21_represntation.pdf
